add models migrations
agibalovsu/Rails pull request #3
Opened 2021-10-26 22:02 UTC by agibalovsu

ADD models and migrations in test_guru

2021-10-27 06:54 UTC, BubuntuClu requested changes

2021-10-27 06:54 UTC, BubuntuClu commented on db/migrate/20211021191854_create_tests.rb
> +
должен быть внешний ключ на категории

2021-10-27 06:54 UTC, BubuntuClu commented on db/migrate/20211026194401_create_questions.rb
> +
должен быть внешний ключ на тесты

2021-10-27 06:54 UTC, BubuntuClu commented on db/migrate/20211026195220_create_answers.rb
> +
должен быть внешний ключ на вопросы

2021-10-27 06:54 UTC, BubuntuClu commented
откати миграции создания таблиц, исправь код и о5 накати

2021-10-27 23:15 UTC, agibalovsu commented
Подскажи, пытаюсь создать миграцию блок внешних ключей add_foreign_key… при откатанных миграциях в которых хочу сделать изменение.Затем накатываю миграции в scheme изменения вижу а в самих миграциях строка не появляется t.reference…?
что я делаю не так?
  
>Среда, 27 октября 2021, 9:54 +03:00 от BubuntuClu ***@***.***>:
> 
> 
>откати миграции создания таблиц, исправь код и о5 накати
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Сергей Агибалов
 

2021-10-28 21:13 UTC, BubuntuClu approved these changes

2021-10-28 21:13 UTC, BubuntuClu commented on db/migrate/20211026194401_create_questions.rb
> +
`t.references :test, foreing_key: true`
нужно сказать что внешний ключ надо создать

2021-11-04 21:25 UTC, merged