add seeds and models user and test
agibalovsu/Rails pull request #4
Opened 2021-10-30 16:13 UTC by agibalovsu

1. добавлены первичные данные в файл seeds.rb
2. добавлен метод класса в файл test.rb
3. добавлен инстанс метод в файл user.rb

2021-10-30 19:06 UTC, BubuntuClu requested changes

2021-10-30 19:06 UTC, BubuntuClu commented on app/models/test.rb
> +    by_category(category).order(title: :desc).pluck(:title)
что такое `by_category`? это метод какой-то? где он объявлен?

2021-10-30 19:06 UTC, BubuntuClu commented on app/models/user.rb
> +    self.tests.where("level = ?" level)
что такое `tests`? нет никакого объявления этого метода

2021-11-01 07:41 UTC, BubuntuClu requested changes

2021-11-01 07:41 UTC, BubuntuClu commented on db/migrate/20211026195007_create_users.rb
> +      t.references :test, foreign_key: true
1 - нельзя править миграции, которые уже слиты в мастер ветку. надо откатить эту миграцию и удалить строчку из этого файла
2 - эта связь не делает то, чего ты хочешь. она не отвечает за прохождение

2021-11-01 07:41 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins('join users on users.test_id = tests.id').where(tests: { level: level }).pluck(:title)
для этого запроса тебе потребуется сделать доп таблицу, так как у тебя связь многи-ко-многим

2021-11-02 06:40 UTC, BubuntuClu requested changes

2021-11-02 06:40 UTC, BubuntuClu commented on db/migrate/20211101191623_create_test_passages.rb
> +    create_table :test_passages do |t|
подсматривать не очень хорошо. но если посмотрел, то копировать надо не все что увидел, а только то что нужно тебе.

что сейчас будут делать столбцы correct_answers и passed?

2021-11-02 06:40 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins('join users on users.test_id = tests.id').where(tests: { level: level }).pluck(:title)
не заменил таблицу в джойне

2021-11-02 06:45 UTC, agibalovsu commented
Не просто подмострел а изучил в goglе почти все что есть по этому вопросу))) 
Correct_answers отвечает за начаты но ещё незаконченный тест
Passed за пройденные тесты))) 
--
Отправлено из Mail.ru для Android вторник, 02 ноября 2021г., 09:40 +03:00 от BubuntuClu  ***@***.*** :

***@***.*** requested changes on this pull request.
>----------------------------------------------------------------------
>In  db/migrate/20211101191623_create_test_passages.rb :
> @@ -0,0 +1,11 @@
>+class CreateTestPassages < ActiveRecord::Migration[6.1]
>+  def change
>+    create_table :test_passages do |t|
>
>подсматривать не очень хорошо. но если посмотрел, то копировать надо не все что увидел, а только то что нужно тебе.
>что сейчас будут делать столбцы correct_answers и passed?
>----------------------------------------------------------------------
>In  app/models/user.rb :
> @@ -1,2 +1,5 @@
> class User < ApplicationRecord
>+  def tests_by_level(level)
>+    Test.joins('join users on users.test_id = tests.id').where(tests: { level: level }).pluck(:title)
>
>не заменил таблицу в джойне
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

2021-11-02 18:18 UTC, BubuntuClu commented
> Correct_answers отвечает за начаты но ещё незаконченный тест Passed за пройденные тесты)))

а для чего тебе эта информация? ты добавляешь просто, потому что там где-то написали, что нужны будут такие столбцы

2021-11-02 18:20 UTC, BubuntuClu commented on db/seeds.rb
> +  { title: 'Основы Ruby', level: 0,   category_id: 1 },
было правильней чем сейчас стало. хардкодить id нельзя.
`category_id: categories[1].id` используй ID объектов

2021-11-02 18:25 UTC, agibalovsu commented
Нет потому что в условии задачи написано проходит или уже  завершил тест, я подумал как это обозначить посмотрел куча материала и нашёл такой вариант, значит в будущем понадобится, вот такая логика была
--
Отправлено из Mail.ru для Android вторник, 02 ноября 2021г., 21:18 +03:00 от BubuntuClu  ***@***.*** :

>>Correct_answers отвечает за начаты но ещё незаконченный тест Passed за пройденные тесты)))
>а для чего тебе эта информация? ты добавляешь просто, потому что там где-то написали, что нужны будут такие столбцы
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

2021-11-04 21:27 UTC, merged